// Generated by CoffeeScript 1.6.2
'use strict';describe('Controller: MainCtrl', function() {
  var MainCtrl, scope;

  beforeEach(module('matchApp'));
  MainCtrl = {};
  scope = {};
  beforeEach(inject(function($controller, $rootScope) {
    scope = $rootScope.$new();
    return MainCtrl = $controller('MainCtrl', {
      $scope: scope
    });
  }));
  return it('should have app info in the configuration', function() {
    return expect(scope.app).not.toBeNull;
  });
});
