// Generated by CoffeeScript 1.6.2
'use strict';
var matchApp;

matchApp = angular.module('matchApp', ['ngCookies', 'ngResource', 'ngSanitize', 'ngRoute']);

matchApp.config([
  '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
    $locationProvider.html5Mode(true);
    $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    });
    $routeProvider.otherwise;
    return {
      redirectTo: '/'
    };
  }
]);
